### ISSUE TITLE
[Scoreboard] Data retrieval

### ISSUE THREAD

**Issue by donaldong** [progteam/parrot#17]
As part of #16, we need to retrieve data from Kattis by scrapping `https://open.kattis.com/users/<user-handle>`.

The function would take `user-handle` as the argument, and returns/raises
- Error404: User does not exist
- ErrorInvalid: User is not listed under CSUMB. We need to inform the user to choose CSUMB in the settings or contact the admins for people who don't represent CSUMB but still want to be part of the scoreboard.
- points: A floating point number represents the current points of that user.

**Comment by Samwest5** [comment]
For the errors Error404 and ErrorInvalid, are those to be returned as strings?

**Comment by donaldong** [comment]
I was thinking about something like
```
class Error404(Exception):
  pass
```
So we can raise and catch it. I think it's more readable this way comparing to some special values as error code :)
