### ISSUE TITLE
Fix the security vulnerability

### ISSUE THREAD

**Issue by donaldong** [progteam/parrot#3]
As people may have noticed, GitHub sent a security vulnerability alert. Fixing the vulnerability involves updating the Django version. Here is [the alert](https://github.com/progteam/parrot/network/alerts).

**Comment by FernandoCaudillo10** [comment]
Are we going to allow any Django version above 2.1.6, `django >= 2.1.6`, or are we going to stick with a specific version? @donaldong

**Comment by donaldong** [comment]
@FernandoCaudillo10 Maybe we should use version exactly `2.1.6`?

**Comment by FernandoCaudillo10** [comment]
I feel that this would be better for consistency. This would keep people locked to the same version until we make a consensus to move on to another version if needed. @donaldong

**Comment by donaldong** [comment]
@FernandoCaudillo10 Sounds good!
